FROM ubuntu:16.04

RUN apt-get update -qq && apt-get install -qqy \
    git wget bzip2 file unzip libtool pkg-config cmake build-essential \
    automake yasm gettext autopoint vim python git-svn ninja-build \
    subversion && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*


RUN git config --global user.name "LLVM MinGW" && \
    git config --global user.email root@localhost

WORKDIR /build

ARG CORES=4

ENV TOOLCHAIN_PREFIX=/opt/llvm-mingw

# Build LLVM
COPY build-llvm.sh .
RUN ./build-llvm.sh $TOOLCHAIN_PREFIX

ENV TOOLCHAIN_ARCHS="x86_64"

# Install the usual $TUPLE-clang binaries
COPY wrappers/*.sh ./wrappers/
COPY install-wrappers.sh .
RUN ./install-wrappers.sh $TOOLCHAIN_PREFIX

# Build MinGW-w64
COPY build-mingw-w64.sh .
RUN ./build-mingw-w64.sh $TOOLCHAIN_PREFIX

# Build compiler-rt
COPY build-compiler-rt.sh .
RUN ./build-compiler-rt.sh $TOOLCHAIN_PREFIX

# Build mingw-w64's winpthreads
COPY build-mingw-w64-winpthreads.sh .
RUN ./build-mingw-w64-winpthreads.sh $TOOLCHAIN_PREFIX

# Build C test applications
ENV PATH=$TOOLCHAIN_PREFIX/bin:$PATH

COPY test/*.c ./test/
RUN cd test && \
    for arch in $TOOLCHAIN_ARCHS; do \
        for test in hello hello-tls crt-test; do \
            $arch-w64-mingw32-clang $test.c -o $test-$arch.exe || exit 1; \
        done; \
    done

COPY test/*.rc ./test/
COPY test-windres.sh .
RUN ./test-windres.sh $TOOLCHAIN_PREFIX

# Build libunwind/libcxxabi/libcxx
COPY build-libcxx.sh merge-archives.sh ./
RUN ./build-libcxx.sh $TOOLCHAIN_PREFIX

# Build C++ test applications
COPY test/*.cpp ./test/
RUN cd test && \
    for arch in $TOOLCHAIN_ARCHS; do \
        for test in hello-cpp hello-exception; do \
            $arch-w64-mingw32-clang++ $test.cpp -o $test-$arch.exe || exit 1; \
        done; \
    done

# Build libssp
COPY build-libssp.sh libssp-Makefile ./
RUN ./build-libssp.sh $TOOLCHAIN_PREFIX

# Strip the final toolchain. (This doesn't reduce the total docker image
# size as long as it is in a separate RUN layer though.)
COPY strip-llvm.sh .
RUN ./strip-llvm.sh $TOOLCHAIN_PREFIX

ENV TEST_ARCH=x86_64
ENV TEST_TRIPLET=$TEST_ARCH-w64-mingw32
ENV TEST_ROOT=/build/demo
ENV PKG_CONFIG_LIBDIR=/build/demo/lib/pkgconfig

RUN wget http://zlib.net/zlib-1.2.11.tar.gz && \
    tar -zxvf zlib-1.2.11.tar.gz

RUN cd zlib-1.2.11 && \
    make -f win32/Makefile.gcc PREFIX=$TEST_TRIPLET- SHARED_MODE=1 -j4 && \
    make -f win32/Makefile.gcc install SHARED_MODE=1 INCLUDE_PATH=$TEST_ROOT/include LIBRARY_PATH=$TEST_ROOT/lib BINARY_PATH=$TEST_ROOT/bin
